//go:build go1.17 && arm64
// +build go1.17,arm64

/*
 * Copyright 2021 ByteDance Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package loader

import (
	"runtime"
	"runtime/debug"
	"strconv"
	"testing"
	"unsafe"

	"github.com/bytedance/sonic/loader/internal/rt"
	"github.com/stretchr/testify/require"
)

func TestLoadARM64(t *testing.T) {
	if runtime.GOARCH != "arm64" {
		t.Skip("This test uses ARM64-specific bytecode")
	}

	var hstr string

	type TestFunc func(i *int, hook func(i *int)) int
	var hook = func(i *int) {
		runtime.GC()
		debug.FreeOSMemory()
		hstr = ("hook" + strconv.Itoa(*i))
		runtime.GC()
		debug.FreeOSMemory()
	}

	// ARM64 bytecode generated by Go compiler for:
	// func(i *int, hook func(i *int)) int {
	//     var t = *i
	//     hook(i)
	//     return t + *i
	// }
	//
	// Stack layout (32 bytes frame):
	// sp+40: saved i pointer (arg area, outside frame)
	// sp+24: FP (frame pointer)
	// sp+16: saved old value of *i (local var)
	// sp+0:  return address (LR)
	bc := []byte{
		0xfe, 0x0f, 0x1e, 0xf8, // (0x00) MOVD.W R30, -32(RSP)  ; save LR and alloc stack
		0xfd, 0x83, 0x1f, 0xf8, // (0x04) MOVD R29, -8(RSP)     ; save FP
		0xfd, 0x23, 0x00, 0xd1, // (0x08) SUB $8, RSP, R29      ; set up FP
		0xe0, 0x17, 0x00, 0xf9, // (0x0c) MOVD R0, 40(RSP)      ; save i pointer (arg area)
		0x02, 0x00, 0x40, 0xf9, // (0x10) MOVD (R0), R2         ; R2 = *i
		0xe2, 0x0b, 0x00, 0xf9, // (0x14) MOVD R2, 16(RSP)      ; save old value
		0x23, 0x00, 0x40, 0xf9, // (0x18) MOVD (R1), R3         ; R3 = hook.fn
		0xfa, 0x03, 0x01, 0xaa, // (0x1c) MOVD R1, R26          ; save R1 to R26 (context)
		0x60, 0x00, 0x3f, 0xd6, // (0x20) CALL (R3)             ; call hook
		0xe1, 0x17, 0x40, 0xf9, // (0x24) MOVD 40(RSP), R1      ; restore i pointer
		0x21, 0x00, 0x40, 0xf9, // (0x28) MOVD (R1), R1         ; R1 = *i (new value)
		0xe2, 0x0b, 0x40, 0xf9, // (0x2c) MOVD 16(RSP), R2      ; restore old value
		0x40, 0x00, 0x01, 0x8b, // (0x30) ADD R1, R2, R0        ; R0 = old + new
		0xfd, 0xfb, 0x7f, 0xa9, // (0x34) LDP -8(RSP), (R29, R30) ; restore FP, LR
		0xff, 0x83, 0x00, 0x91, // (0x38) ADD $32, RSP, RSP     ; dealloc stack
		0xc0, 0x03, 0x5f, 0xd6, // (0x3c) RET                   ; return
	}

	size := uint32(len(bc))
	fn := Func{
		ID:          0,
		Flag:        0,
		ArgsSize:    16,
		EntryOff:    0,
		TextSize:    size,
		DeferReturn: 0,
		FileIndex:   0,
		Name:        "dummy_arm64",
	}

	fn.Pcsp = &Pcdata{
		{PC: size, Val: 32},
	}

	fn.Pcline = &Pcdata{
		{PC: 0x04, Val: 0},
		{PC: 0x0c, Val: 1},
		{PC: 0x24, Val: 2},
		{PC: size, Val: 3},
	}

	fn.Pcfile = &Pcdata{
		{PC: size, Val: 0},
	}

	fn.PcUnsafePoint = &Pcdata{
		{PC: size, Val: PCDATA_UnsafePointUnsafe},
	}

	fn.PcStackMapIndex = &Pcdata{
		{PC: size, Val: 0},
	}

	args := rt.StackMapBuilder{}
	args.AddField(true) // i *int
	args.AddField(true) // hook.fn
	fn.ArgsPointerMaps = args.Build()

	locals := rt.StackMapBuilder{}
	locals.AddField(false) // old value (int, non-pointer)
	locals.AddField(false) // padding/alignment
	fn.LocalsPointerMaps = locals.Build()

	rets := Load(bc, []Func{fn}, "dummy_arm64_module", []string{"github.com/bytedance/sonic/dummy_arm64.go"})
	println("func address ", *(*unsafe.Pointer)(rets[0]))

	f := *(*TestFunc)(unsafe.Pointer(&rets[0]))
	i := 1
	j := f(&i, hook)
	require.Equal(t, 2, j)
	require.Equal(t, "hook1", hstr)

	fi := runtime.FuncForPC(*(*uintptr)(rets[0]))
	require.Equal(t, "dummy_arm64", fi.Name())
	file, line := fi.FileLine(0)
	require.Equal(t, "github.com/bytedance/sonic/dummy_arm64.go", file)
	require.Equal(t, 0, line)
}
